name: Tweet Year Progress Banana

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # 9:00 AM ET (13:00 UTC)
    - cron: '0 22 * * *' # 6:00 PM ET (22:00 UTC)

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tweetbot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: python tweetbot.py

      - name: Commit and push progress
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          git add progress_state.json activity.log
          if ! git diff --quiet || ! git diff --staged --quiet; then
            git commit -m "Update progress"
            git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${GITHUB_REPOSITORY}.git
            git push origin HEAD:main || echo "Push failed"
          else
            echo "No changes to commit"
          fi

      - name: Debug token usage
        run: |
          echo "GH_PAT is set? ${GH_PAT}"
          git remote -v
          git config --list
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

