name: Tweet Year Progress Banana

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *' # 9:00 AM ET (13:00 UTC)
    - cron: '0 22 * * *' # 6:00 PM ET (22:00 UTC)

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tweetbot
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: python tweetbot.py

      - name: Commit and push progress
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add progress_state.json activity.log
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update progress" && git push https://gtenxbox:${GH_PAT}@github.com/gtenxbox/bfksdjcx.git HEAD:main)
# Force refresh
